export {
  REFERENCE_TOPICS,
  appendNarrationChunk,
  appendThinkingChunk,
  dropTrailingSummaryEcho,
  isDeployProjectActivity,
  lastFinishedAssistant,
  presentToolActivity,
  resolveDeployOffer,
  sealOpenThinking,
  toolActionTier,
  type DeployOfferMessage,
  type ReferenceTopic,
  type ToolAction,
  type ToolPresentation,
} from '../../shared/timeline.ts';
